//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHelloWorld")]
public interface IHelloWorld
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorld/GetWelcomeNotes", ReplyAction="http://tempuri.org/IHelloWorld/GetWelcomeNotesResponse")]
    string GetWelcomeNotes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorld/GetWelcomeNotes", ReplyAction="http://tempuri.org/IHelloWorld/GetWelcomeNotesResponse")]
    System.Threading.Tasks.Task<string> GetWelcomeNotesAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHelloWorldChannel : IHelloWorld, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HelloWorldClient : System.ServiceModel.ClientBase<IHelloWorld>, IHelloWorld
{
    
    public HelloWorldClient()
    {
    }
    
    public HelloWorldClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetWelcomeNotes()
    {
        return base.Channel.GetWelcomeNotes();
    }
    
    public System.Threading.Tasks.Task<string> GetWelcomeNotesAsync()
    {
        return base.Channel.GetWelcomeNotesAsync();
    }
}
